spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CookieHouse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 469509522963-to0sft8e5e14csesq0jdv6507ci5qum0.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile
          kakao:
            client-id: b26eb0b55aeda56951a2455f3a5c6681
            client-secret: ntIC2KFNRL99mGhWEX1IH0m2RDVUYwta
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
jwt:
  secret: b96dfd4fefd8fbcdacf3beddba5139ee89f732223aeeca3156f9b7ffca220fc3
