name: Java CI/CD with Gradle and AWS CodeDeploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Prepare artifacts for deployment
      run: |
        zip -r cookiehouse *
        mkdir -p deploy
        mv cookiehouse.zip deploy/cookiehouse.zip

    - name: Deploy to S3 (GitHub Artifacts)
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: deploy

    - name: AWS 자격증명 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: S3에 배포
      run: aws s3 cp deploy/cookiehouse.zip s3://cookie-house-build/cookiehouse.zip

    - name: AWS CodeDeploy를 사용한 배포
      run: |
        aws deploy create-deployment \
          --application-name CookieHouse \
          --deployment-group-name cookiehouse-group \
          --s3-location bucket=cookie-house-build,key=cookiehouse.zip,bundleType=zip \
          --region ap-northeast-2

    - name: Notify via Email
      run: echo "Notify via Email"  # 이메일 알림 로직을 추가하세요.
